"""empty message

Revision ID: 5409e2a07a22
Revises: 19f79c106bc7
Create Date: 2024-10-26 16:39:26.480105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5409e2a07a22'
down_revision: Union[str, None] = '19f79c106bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('fraction_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'file', ['id'])
    op.create_foreign_key(None, 'file', 'fraction', ['fraction_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'fraction', ['id'])
    op.create_unique_constraint(None, 'point', ['id'])
    op.create_unique_constraint(None, 'user_point_request', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_point_request', type_='unique')
    op.drop_constraint(None, 'point', type_='unique')
    op.drop_constraint(None, 'fraction', type_='unique')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'fraction_id')
    # ### end Alembic commands ###
