"""empty message

Revision ID: 49f342aeff5c
Revises: 531cb2c927f2
Create Date: 2024-10-26 16:01:18.988652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f342aeff5c'
down_revision: Union[str, None] = '531cb2c927f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_title_key', 'event', type_='unique')
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'event_user', ['id'])
    op.add_column('file', sa.Column('event_user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'file', ['id'])
    op.drop_constraint('file_user_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'event_user', ['event_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('file', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key('file_user_id_fkey', 'file', 'event_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'event_user_id')
    op.drop_constraint(None, 'event_user', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.create_unique_constraint('event_title_key', 'event', ['title'])
    # ### end Alembic commands ###
