"""empty message

Revision ID: 9810fc8a56e9
Revises: 472199ddbf53
Create Date: 2024-10-27 00:37:08.763636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9810fc8a56e9'
down_revision: Union[str, None] = '472199ddbf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movement', sa.Column('model', sa.String(), nullable=False))
    op.drop_constraint('movement_mark_key', 'movement', type_='unique')
    op.create_unique_constraint(None, 'movement', ['model'])
    op.create_unique_constraint(None, 'movement', ['id'])
    op.drop_column('movement', 'mark')
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'user_movement', ['id'])
    op.create_unique_constraint(None, 'user_product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_product', type_='unique')
    op.drop_constraint(None, 'user_movement', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.add_column('movement', sa.Column('mark', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movement', type_='unique')
    op.drop_constraint(None, 'movement', type_='unique')
    op.create_unique_constraint('movement_mark_key', 'movement', ['mark'])
    op.drop_column('movement', 'model')
    # ### end Alembic commands ###
