"""empty message

Revision ID: d0b5bc495e5a
Revises: 9810fc8a56e9
Create Date: 2024-10-27 00:40:26.889891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b5bc495e5a'
down_revision: Union[str, None] = '9810fc8a56e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movement_model_key', 'movement', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movement_model_key', 'movement', ['model'])
    # ### end Alembic commands ###
