"""empty message

Revision ID: e2a99c824d80
Revises: 7a9e23dd304b
Create Date: 2024-10-26 16:26:36.000212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a99c824d80'
down_revision: Union[str, None] = '7a9e23dd304b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movement', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'user_movement', ['id'])
    op.add_column('user_product', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'user_product', ['id'])
    op.drop_constraint('user_product_movement_id_fkey', 'user_product', type_='foreignkey')
    op.create_foreign_key(None, 'user_product', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_product', 'movement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_product', sa.Column('movement_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_product', type_='foreignkey')
    op.create_foreign_key('user_product_movement_id_fkey', 'user_product', 'movement', ['movement_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'user_product', type_='unique')
    op.drop_column('user_product', 'product_id')
    op.drop_constraint(None, 'user_movement', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'movement', type_='unique')
    # ### end Alembic commands ###
