apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-microservice
  labels:
    app: action-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-microservice
  template:
    metadata:
      labels:
        app: action-microservice
    spec:
      containers:
        - name: action-microservice
          image: xoriax/green-rostov-action:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: action-microservice

spec:
  selector:
    app: action-microservice

  ports:
    - name: web
      port: 4000
      targetPort: web
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: action-microservice-ingress-route
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: Host(`dstu-actions.labofdev.ru`)
      services:
        - kind: Service
          name: action-microservice
          port: 4000
