apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-microservice
  labels:
    app: point-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-microservice
  template:
    metadata:
      labels:
        app: point-microservice
    spec:
      containers:
        - env:
            - name: SECRET_KEY
              value: AS;DKFJLH197H8FYOIutyo&tyouyp(8UY%&^())
            - name: DB_LINK
              value: postgresql+asyncpg://postgresql:postgresql@10.104.229.203:5432/point
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: microservice-secrets
                  key: algorithm
            - name: S3_BUCKET_NAME
              value: test-bucket
            - name: S3_URL
              value: s3.labofdev.ru
            - name: MINIO_ACCESS_KEY
              value: NCitCJJY49q8ZY4YiLP4
            - name: MINIO_SECRET_KEY
              value: GdUd3KB6KJOEAP7YStpJmAO9QFX9C25EId2XXn5C
          name: point-microservice
          image: xoriax/green-rostov-point:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: point-microservice

spec:
  selector:
    app: point-microservice

  ports:
    - name: web
      port: 4002
      targetPort: web
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: point-microservice-ingress-route
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: Host(`dstu-point.labofdev.ru`)
      services:
        - kind: Service
          name: point-microservice
          port: 4002
